#!/usr/bin/env bash

set -e

PARENT_PATH=$(dirname $(
  cd $(dirname $0)
  pwd -P
))

OS=$(go env GOOS)
ARCH=$(go env GOARCH)

# Resolve datadir the same way btcutil.AppDataDir does
case "$OS" in
  darwin)
    DATADIR="$HOME/Library/Application Support/Nigiri"
    ;;
  linux)
    DATADIR="$HOME/.nigiri"
    ;;
  *)
    echo "Unsupported OS: $OS"
    exit 1
    ;;
esac

pushd "$PARENT_PATH" > /dev/null

echo "Building..."
./scripts/build

echo "Installing binary to /usr/local/bin/nigiri..."
sudo cp "build/nigiri-$OS-$ARCH" /usr/local/bin/nigiri

echo "Syncing resources to $DATADIR..."
cp "cmd/nigiri/resources/docker-compose.yml" "$DATADIR/docker-compose.yml"
mkdir -p "$DATADIR/ui"
cp -r cmd/nigiri/resources/ui/. "$DATADIR/ui/"

popd > /dev/null

echo "Done. $(nigiri version)"
